## YAML Template.
Kaapiii\Entity\Entity:
    type: entity
    table: testYamlEntities
    gedmo: 
        translation:
            locale: locale
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string